spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pet_supplier_db
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  kafka:
    consumer:
      group-id: "supplier-group"
      client-id: "supplier-service-consumer"
      auto-offset-reset: earliest

application:
  kafka:
    topic: supplier-request-event

broker:
  bootstrap-server: localhost:9092

server:
  port: 8082
